AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for EKS cluster & nodes

Parameters:
  ProjectName:
    Type: String

Resources:
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: eks.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - { Key: Project, Value: !Ref ProjectName }

  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - { Key: Project, Value: !Ref ProjectName }

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref NodeRole]

Outputs:
  ClusterRoleArn:
    Value: !GetAtt EksClusterRole.Arn
    Export: { Name: !Sub '${ProjectName}:ClusterRoleArn' }
  NodeRoleArn:
    Value: !GetAtt NodeRole.Arn
    Export: { Name: !Sub '${ProjectName}:NodeRoleArn' }